config/routes.rb
Rails.application.routes.draw do

  root 'resumes#index'

  resources :users

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  resources :resumes do
    resource :downloads
    resource :displays
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resumany</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav id="nav_links" class="line">
    <div id="left_nav" class="item">
      <%= link_to image_tag("resuMANY_logo.png", :class => "logo"), "/resumes/" %>
    </div>
    <div id="center_nav" class="item">
      <% if session[:user_id] && @current_user.resume %>
        <%= link_to image_tag("cv_icon.svg", :class => "cv_icon"), "/resumes/cv" %>
        <!-- Edit or New, Depends on if CV has yet been generated -->
        <%= link_to image_tag("edit_icon.svg", :class => "icon"), edit_resume_path(@resume) %>
        <!-- Only visible on /resumes/cv and /resumes/tags pages -->
        <%= link_to image_tag("download_icon.svg", :class => "icon"), edit_resume_downloads_path(@resume) %>
        <%= link_to image_tag("sort_icon.svg", :class => "icon"), edit_resume_displays_path(@resume) %>
      <% end %>

    </div>
    <div id="right_nav" class="item">
      <% if session[:user_id].nil? %>
        <%= link_to "Log In", login_path, id: "login" %>
      <% else %>
        <%= link_to "#{@current_user.email} Log Out", logout_path, method: :delete, id: "login" %>
      <% end %>
    </div>
    <div id="right_pad" class="item"></div>
  </nav>
  <div id="yield_container">
    <%= yield %>
  </div>
</body>
</html>